sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  - composer
  - $HOME/.composer/cache

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm install
  - npm run build

script:
  - phpunit
